version: '3.8'

services:
  db-envios-servicio:
    image: mysql:8.0
    container_name: mysql_envios
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_amazorg_envios
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3314:3306"
    networks:
      - red_interna_envios
    volumes:
      - persistencia_db_envios:/var/lib/mysql

  workspace-java-envios:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion_envios
    ports:
      - "8088:8088"
    depends_on:
      - db-envios-servicio
    networks:
      - red_interna_envios
    command: tail -f /dev/null
    volumes:
      - ./codigo-fuente:/app
    working_dir: /app

networks:
  red_interna_envios:

volumes:
  persistencia_db_envios: